/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermoConsentimentoRouteImport } from './routes/termo-consentimento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LpOnboardingRouteImport } from './routes/lp/onboarding'

const TermoConsentimentoRoute = TermoConsentimentoRouteImport.update({
  id: '/termo-consentimento',
  path: '/termo-consentimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LpOnboardingRoute = LpOnboardingRouteImport.update({
  id: '/lp/onboarding',
  path: '/lp/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/termo-consentimento': typeof TermoConsentimentoRoute
  '/lp/onboarding': typeof LpOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/termo-consentimento': typeof TermoConsentimentoRoute
  '/lp/onboarding': typeof LpOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/termo-consentimento': typeof TermoConsentimentoRoute
  '/lp/onboarding': typeof LpOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/termo-consentimento' | '/lp/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/termo-consentimento' | '/lp/onboarding'
  id: '__root__' | '/' | '/termo-consentimento' | '/lp/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TermoConsentimentoRoute: typeof TermoConsentimentoRoute
  LpOnboardingRoute: typeof LpOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termo-consentimento': {
      id: '/termo-consentimento'
      path: '/termo-consentimento'
      fullPath: '/termo-consentimento'
      preLoaderRoute: typeof TermoConsentimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/onboarding': {
      id: '/lp/onboarding'
      path: '/lp/onboarding'
      fullPath: '/lp/onboarding'
      preLoaderRoute: typeof LpOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TermoConsentimentoRoute: TermoConsentimentoRoute,
  LpOnboardingRoute: LpOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
